server:
  port: 8607
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      routes:
        - id: blog-service
          uri: lb://blogService
          predicates:
              - Path=/mogu-web/**
            #      解决跨域问题
      globalcors:
        add-to-simple-url-handler-mapping: true #解决options请求被拦截问题
        corsconfigurations:
          '[/**]': #这里表示会拦截什么请求
            allowed-origins: #允许那些网站的跨域请求
              - "http://localhost:9527"
            allowed-methods: #允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
            allowed-headers:
              - "*" #允许在请求中携带头信息
            allowCredentials: true #是否允许携带cookie
            maxAge: 360000 #这次跨域监测的有效期,浏览器将不再询问,直接放行

