server:
  port: 8608
spring:
  application:
    name: blog-service
  datasource:
    username: root
    url: jdbc:mysql://192.168.239.100:3306/mogu_blog
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      server-addr: localhost:8848
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: org.example.entity
logging:
  level:
    one: debug
